pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "MusicConverter_MIUI_Pro"

include ':app'
include ':ffmpeg-kit'

project(':ffmpeg-kit').projectDir =
        file('ffmpeg-kit/android/ffmpeg-kit-android-lib')